#!/usr/bin/env bash

FILE_PATH="${1}" # Full path of the highlighted file
WIDTH="${2}"     # Width of the preview pane (number of fitting characters)
HEIGHT="${3}"    # Height of the preview pane (number of fitting characters)
X="${4}"         # X coordinate of the preview pane
Y="${5}"         # Y coordinate of the preview pane

set -eu
kitty +kitten icat --clear --stdin no --transfer-mode file < /dev/null > /dev/tty
echo "$(file -Lb --mime-type "$FILE_PATH")"
if [[ "$(file -Lb --mime-type "$FILE_PATH")" =~ ^image ]]; then
    echo "in here"
    kitty +kitten icat --silent --stdin no --transfer-mode memory --place "${WIDTH}x${HEIGHT}@${X}x${Y}" "${FILE_PATH}" < /dev/null > /dev/tty
else
    bat "${FILE_PATH}"
fi


