#!/usr/bin/env bash
tmux new-window
tmux select-window -t 2
tmux send-keys "ngrok http 8190" Enter
sleep 2

tmux select-window -t 1
ngrok_url=$(curl -s localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')
echo $ngrok_url

tmux split-window -v -p 30 "API_BASE_URL=$ngrok_url npm run start:dev"
tmux select-pane -t :.+
tmux send-keys "nvim" Enter
